version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: yingxindocker/fishery:cwebserver
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.2"
          memory: 2000M
      restart_policy:
        condition: on-failure
    ports:
      - "8000:8000"
    networks:
      - webnet
networks:
  webnet: